# Generated by Django 4.0.4 on 2022-05-14 20:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('Image', models.ImageField(upload_to='')),
                ('PlotNo', models.CharField(max_length=20)),
                ('Area', models.FloatField()),
                ('Dev_plotno', models.IntegerField()),
                ('Section', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Historical Sites',
            },
        ),
        migrations.CreateModel(
            name='Sub_counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Sub_counties',
            },
        ),
    ]
