# Generated by Django 4.0.5 on 2022-06-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritagesites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsite',
            old_name='Image',
            new_name='site_image',
        ),
    ]
