# Generated by Django 4.0.5 on 2022-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritagesites', '0002_rename_image_historicalsite_site_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsite',
            old_name='site_image',
            new_name='Image',
        ),
    ]
